vote:
  repicaCount: 3
  image:
    repository: "schoolofdevops/vote"
    tag: "v7"
  service:
    type: NodePort
    port: 80
    nodePort: 30300
  options:
    A: "AAA"
    B: "BBB"

redis:
  repicaCount: 1
  image:
    repository: "redis"
    tag: "alpine"
  service:
    type: ClusterIP
    port: 6379
